[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18.16.0"

# Configuração para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 